name: Test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  test_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm run test
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: RebeccaStevens/type-to-string
